<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="utf-8">
    <title>Skeleton</title>
    <link rel="stylesheet" href="css/normalize.min.css">
    <link rel="stylesheet" href="css/font-awesome.min.css">
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Open+Sans">
   
    <link rel="stylesheet" href="css/style.css">

</head>
<body>
    <header>
<img src="img/logo.png" class="img"/>
    </header>
    <main>
       <section>
          
           
          <div id="heros" class="face-att2g"></div> 
          <div id="monstre1"></div>
          <div id="monstre2"></div>
          <div id="monstre3"></div>
          <div id="monstre4"></div>
          <div id="monstre5"></div>
          <div id="monstre6"></div>
           
       </section>

       
    </main>
<footer>
<img src="img/brlogo.png" class="img"/>

</footer>




    <script src="js/script.js"></script>
</body>
</html>